dt: 0.0041666667
substeps: 4
steps: -1
gravity: [0.0, -9.8, 0.0]
linear_damping: 0
angular_damping: 0
objects:
  - type: cuboid
    dyn_type: free
    size: [0.6, 0.6, 0.6]
    position: [0.0, 0.3, 0.0]
    velocity: [0.0, 0.0, 0.0]
    rotation_deg: [0.0, 0.0, 0.0]
    angular_velocity: [0.0, 0.0, 0.0]
    mass: 1.0
    color: [0.8, 0.2, 0.2]
  - type: cuboid
    dyn_type: free
    size: [0.6, 0.6, 0.6]
    position: [0.0, 0.9, 0.0]
    velocity: [0.0, 0.0, 0.0]
    rotation_deg: [0.0, 0.0, 0.0]
    angular_velocity: [0.0, 0.0, 0.0]
    mass: 1.0
    color: [0.2, 0.8, 0.2]
  - type: cuboid
    dyn_type: free
    size: [0.6, 0.6, 0.6]
    position: [0.0, 1.5, 0.0]
    velocity: [0.0, 0.0, 0.0]
    rotation_deg: [0.0, 0.0, 0.0]
    angular_velocity: [0.0, 0.0, 0.0]
    mass: 1.0
    color: [0.2, 0.2, 0.8]
  - type: cuboid
    dyn_type: free
    size: [0.6, 0.6, 0.6]
    position: [0.0, 2.1, 0.0]
    velocity: [0.0, 0.0, 0.0]
    rotation_deg: [0.0, 0.0, 0.0]
    angular_velocity: [0.0, 0.0, 0.0]
    mass: 1.0
    color: [0.8, 0.8, 0.8]
  - type: cuboid
    dyn_type: freeze
    size: [10.0, 0.01, 10.0]
    rotation_deg: [0.0, 0.0, 0.0]
    position: [0.0, -0.005, 0.0]
    color: [0.8, 0.8, 0.8]